Repository Black-Kamelia/Hedera, pull requests merged in 2022-07, with the labels that each got.

#17 Pageable responses + finalized user CRUD
  gradle.properties
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/database/Connection.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Serialization.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/pageable/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Serializers.kt
  server/src/test/kotlin/com/kamelia/jellyfish/rest/UserTest.kt
Labels: Enhancement

#18 Authorization with JWT
  client/package-lock.json
  client/package.json
  client/src/components/TheWelcome.vue
  gradle.properties
  postman/Jellyfish.postman_collection.json
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/jellyfish/Application.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/TokenPair.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Authentication.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/CORS.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Routing.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Serialization.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/auth/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/auth/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/auth/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Environment.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Extensions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/QueryResult.kt
  server/src/main/resources/application.conf
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/test/kotlin/com/kamelia/jellyfish/ApplicationTest.kt
  server/src/test/kotlin/com/kamelia/jellyfish/TestUtils.kt
  server/src/test/kotlin/com/kamelia/jellyfish/rest/AuthTest.kt
  server/src/test/kotlin/com/kamelia/jellyfish/rest/UserTest.kt
  server/src/test/resources/db/data/users.csv
Labels: Enhancement, Feature request

#23 Files CRUD
  Jenkinsfile
  README.md
  postman/Jellyfish.postman_collection.json
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/database/Connection.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Routing.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Serialization.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/auditable/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Extensions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Serializers.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/test/kotlin/com/kamelia/jellyfish/TestUtils.kt
  server/src/test/resources/db/data/users.csv
Labels: Enhancement

#26 Replaced ExceptionAdvisor API with the idiomatic StatusPages plugin
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/jellyfish/Application.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisor.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Requests.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Advisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/auth/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
Labels: Enhancement

#25 Added support for page definitions
  .gitignore
  Jenkinsfile
  build.gradle.kts
  client/package-lock.json
  client/package.json
  client/vite.config.ts
  gradle.properties
  server/.gitignore
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/jellyfish/Application.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisor.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/QueryResult.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Requests.kt
  server/src/main/kotlin/com/kamelia/jellyfish/database/Connection.kt
  server/src/main/kotlin/com/kamelia/jellyfish/database/Liquibase.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Advisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/plugins/Authentication.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/auth/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/auth/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/pageable/DTO.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/pageable/Filter.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/pageable/Sorter.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Environment.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Extensions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/FileUtils.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/MimeTypes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Serializers.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/main/resources/db/db.changelog-master.xml
  server/src/main/resources/mime-type-catalog.csv
  server/src/test/kotlin/com/kamelia/jellyfish/TestUtils.kt
  server/src/test/kotlin/com/kamelia/jellyfish/rest/FileTest.kt
  server/src/test/resources/db/changelog/db.test-data.xml
  server/src/test/resources/db/data/files.csv
  server/src/test/resources/db/db.changelog-test.xml
  server/src/test/resources/test_files/test.txt
Labels: Enhancement, Feature request

#27 Update Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
Labels: Bug fix
