Repository Black-Kamelia/Hedera, pull requests merged in 2022-06, with the labels that each got.

#10 Added support for semiautomatic table auditing
  server/src/main/kotlin/com/kamelia/jellyfish/rest/core/auditable/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Extensions.kt
Labels: Enhancement, Feature request

#14 ExceptionAdvisor API
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisor.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/ExceptionAdvisors.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Hasher.kt
  server/src/main/kotlin/com/kamelia/jellyfish/core/Requests.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/jellyfish/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Extensions.kt
  server/src/test/kotlin/com/kamelia/jellyfish/util/HasherTest.kt
Labels: Enhancement

#15 Add Liquibase
  gradle.properties
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/jellyfish/Application.kt
  server/src/main/kotlin/com/kamelia/jellyfish/database/Connection.kt
  server/src/main/kotlin/com/kamelia/jellyfish/database/Liquibase.kt
  server/src/main/kotlin/com/kamelia/jellyfish/util/Environment.kt
  server/src/main/resources/db/db.changelog-master.xml
Labels: Documentation
