Repository Black-Kamelia/Hedera, pull requests merged in 2023-09, with the labels that each got.

#170 Redirect from login
  client/app.vue
  client/middleware/auth.ts
  client/pages/login.vue
  client/utils/getRedirectParam.ts
Labels: Enhancement, Feature request

#168 Form on login page is a bit broken
  client/components/pages/configuration/users/CreateUserDialog.vue
  client/components/pages/configuration/users/EditUserDialog.vue
  client/components/pages/profile/security/PasswordUpdater.vue
  client/components/pages/profile/tokens/CreateTokenDialog.vue
  client/composables/useFeedbackFormErrors.ts
  client/nuxt.config.ts
  client/package.json
  client/pages/login.vue
  client/pages/reset-password.vue
  client/pnpm-lock.yaml
Labels: Bug fix

#167 Upload page
  client/components/pages/profile/settings/UploadBehavior.vue
  client/components/pages/upload/FileDrop.vue
  client/components/pages/upload/FileDropFilesSection.vue
  client/composables/upload/useUploadFile.ts
  client/composables/useHumanFileSize.ts
  client/composables/users/useUpdatePassword.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/pages/profile/settings.vue
  client/pages/upload.vue
  client/public/assets/css/dark-theme.css
  client/public/assets/css/light-theme.css
  client/stores/useUserSettings.ts
  client/types/index.d.ts
  client/utils/uploaderConfigs/getSharexConfiguration.ts
  client/utils/uploaderConfigs/getUpicConfiguration.ts
  server/src/main/kotlin/com/kamelia/hedera/core/Actions.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/setting/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/setting/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/setting/Settings.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/main/resources/db/data/default-users-settings.csv
  server/src/test/kotlin/com/kamelia/hedera/rest/UserSettingsTest.kt
  server/src/test/resources/db/data/users-settings.csv
Labels: Feature request

#172 Fix favicon not working + update file code format
  server/.gitignore
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/util/FileUtils.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
  server/src/test/resources/db/data/files.csv
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000001/$0000_00_01
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000001/$0002_01_01
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000001/$0002_02_01
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000001/$0002_03_01
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000002/$0002_01_02
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000002/$0002_02_02
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000002/$0002_03_02
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000003/$0002_01_03
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000003/$0002_02_03
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000003/$0002_03_03
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000004/$0002_01_04
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000004/$0002_02_04
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000004/$0002_03_04
  server/src/test/resources/upload/00000000-0000-0000-0000-000000000005/$0006_00_01
Labels: Enhancement, Bug fix

#162 User disk quota
  client/components/input/FormInputFileSize.vue
  client/components/pages/configuration/users/CreateUserDialog.vue
  client/components/pages/configuration/users/EditUserDialog.vue
  client/components/pages/configuration/users/UsersTable.vue
  client/components/pages/profile/security/PasswordUpdater.vue
  client/components/pages/upload/FileDropFilesSection.vue
  client/components/ui/files/FileSizeInput.vue
  client/components/ui/topbar/QuotaPreviewer.vue
  client/components/ui/topbar/Topbar.vue
  client/composables/useFeedbackFormErrors.ts
  client/composables/useHumanFileSize.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/pages/debug/stores.vue
  client/types/index.d.ts
  client/utils/forms.ts
  client/utils/websocketEvents.ts
  server/src/main/kotlin/com/kamelia/hedera/core/Errors.kt
  server/src/main/kotlin/com/kamelia/hedera/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Advisors.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/SessionManager.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/main/resources/db/data/default-users.csv
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/UserTest.kt
  server/src/test/kotlin/com/kamelia/hedera/util/DtoTest.kt
  server/src/test/resources/db/data/files.csv
  server/src/test/resources/db/data/users.csv
Labels: Enhancement

#179 Login redirect broken
  client/app.vue
Labels: Bug fix

#180 Handle deserialization errors
  server/src/main/kotlin/com/kamelia/hedera/core/Errors.kt
  server/src/main/kotlin/com/kamelia/hedera/core/Response.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Advisors.kt
Labels: Bug fix

#166 UI improvements (part 1)
  client/components/pages/files/FiltersDialog.vue
  client/components/pages/upload/FileDrop.vue
  client/components/ui/navigation/BarButton.vue
  client/components/ui/navigation/HorizontalSeparator.vue
  client/components/ui/navigation/TabNavigation.vue
  client/components/ui/navigation/VerticalSeparator.vue
  client/components/ui/navigation/bottombar/BottomBar.vue
  client/components/ui/navigation/sidebar/Sidebar.vue
  client/components/ui/navigation/sidebar/SidebarButton.vue
  client/components/ui/navigation/topbar/Topbar.vue
  client/components/ui/navigation/topbar/elements/QuotaPreviewer.vue
  client/components/ui/navigation/topbar/elements/ThemeSwitcher.vue
  client/components/ui/sidebar/Sidebar.vue
  client/components/ui/sidebar/SidebarButton.vue
  client/components/ui/topbar/Topbar.vue
  client/components/ui/topbar/TopbarSeparator.vue
  client/layouts/centercard.vue
  client/layouts/main.vue
  client/layouts/sidebar.vue
  client/pages/[...all].vue
  client/pages/analytics.vue
  client/pages/configuration.vue
  client/pages/debug.vue
  client/pages/favorites.vue
  client/pages/files.vue
  client/pages/profile.vue
  client/pages/upload.vue
  client/unocss.config.ts
Labels: UI

#173 Force change password implementation (part 2)
  client/app.vue
  client/components/pages/login/PasswordEditionForm.vue
  client/components/ui/navigation/sidebar/SidebarButton.vue
  client/composables/useWebsocketAutoConnect.ts
  client/composables/users/useUpdatePassword.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/middleware/auth.ts
  client/pages/login.vue
  client/utils/getRedirectParam.ts
  server/src/main/kotlin/com/kamelia/hedera/core/Errors.kt
  server/src/main/kotlin/com/kamelia/hedera/core/Event.kt
  server/src/main/kotlin/com/kamelia/hedera/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Authentication.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/SessionManager.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Events.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/main/kotlin/com/kamelia/hedera/util/WebSocketUtils.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Handlers.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Tokens.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/AuthTest.kt
Labels: Enhancement
