Repository Black-Kamelia/Hedera, pull requests merged in 2023-07, with the labels that each got.

#118 116 search endpoints wrongfully are get endpoints with bodies and other posts should return 201
  server/src/main/kotlin/com/kamelia/hedera/core/Response.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/SessionManager.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/test/kotlin/com/kamelia/hedera/TestUtils.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/AuthTest.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/UserTest.kt
Labels: Bug fix

#119 fixed search file url
  client/pages/files.vue
Labels: Bug fix

#126 Update CI
  Jenkinsfile
  README.md
Labels: Enhancement, Technical

#121 Axios: Goodbye 世界
  .gitignore
  client/components/ui/sidebar/Sidebar.vue
  client/composables/axios/types.ts
  client/composables/axios/useAxiosFactory.ts
  client/composables/axios/useAxiosMiddlewares.ts
  client/composables/fileTable/useChangeFileVisibility.ts
  client/composables/fileTable/useDeleteFile.ts
  client/composables/fileTable/useDownloadFile.ts
  client/composables/fileTable/useFeedbackCall.ts
  client/composables/fileTable/useRenameFile.ts
  client/composables/settings/useSetting.ts
  client/composables/settings/useSettingsPage.ts
  client/composables/useAPI.ts
  client/composables/useI18n.ts
  client/composables/useThumbnail.ts
  client/composables/useWebsocketAutoConnect.ts
  client/middleware/auth.ts
  client/package.json
  client/pages/[...all].vue
  client/pages/files.vue
  client/pages/profile.vue
  client/pages/profile/settings.vue
  client/pnpm-lock.yaml
  client/stores/useAuth.ts
  client/types/index.d.ts
  client/utils/events.ts
  client/utils/fetch/$fetchAPI.ts
  client/utils/fetch/api/refresh.ts
  client/utils/fetch/api/types.ts
  client/utils/fetch/api/utils.ts
  client/utils/fetch/interceptors.ts
  client/utils/fetch/useFetchAPI.ts
  client/utils/messages.ts
  client/utils/s.ts
  client/utils/symbols.ts
Labels: Enhancement

#127 Fix debug page
  client/pages/debug/stores.vue
Labels: Bug fix

#128 Upgrades and eslint
  build.gradle.kts
  client/.eslintrc
  client/app.vue
  client/components/input/InputOTP.vue
  client/components/ui/MainToast.vue
  client/components/ui/files/FilesTable.vue
  client/components/ui/files/FilesTableContextMenu.vue
  client/components/ui/files/FiltersDialog.vue
  client/components/ui/files/MediaPreview.vue
  client/composables/fileTable/useChangeFileVisibility.ts
  client/composables/fileTable/useCopyFileLink.ts
  client/composables/fileTable/useDeleteFile.ts
  client/composables/fileTable/useDownloadFile.ts
  client/composables/fileTable/useFilesTable.ts
  client/composables/fileTable/useRenameFile.ts
  client/composables/usePageName.ts
  client/composables/useThumbnail.ts
  client/middleware/auth.ts
  client/middleware/transition.global.ts
  client/nuxt.config.ts
  client/package.json
  client/pages/debug.vue
  client/pages/files.vue
  client/pages/login.vue
  client/pnpm-lock.yaml
  client/stores/useAuth.ts
  client/stores/useFilesFilters.ts
  client/stores/useUserSettings.ts
  client/utils/OTPUtils.ts
  client/utils/fetch/$fetchAPI.ts
  client/utils/fetch/api/refresh.ts
  client/utils/fetch/api/types.ts
  client/utils/fetch/api/utils.ts
  client/utils/fetch/interceptors.ts
  client/utils/fetch/useFetchAPI.ts
  gradle.properties
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/hedera/util/FileUtils.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Serializers.kt
Labels: Technical

#130 Fix continuous integration
  Jenkinsfile
Labels: Technical

#134 Quick theme switcher
  client/components/pages/profile/settings/PreferredTheme.vue
  client/components/ui/topbar/ThemeSwitcher.vue
  client/components/ui/topbar/Topbar.vue
Labels: Enhancement

#131 Files table pagination
  Jenkinsfile
  client/app.vue
  client/components/pages/files/ActionButtons.vue
  client/components/pages/files/FilesTable.vue
  client/components/pages/files/FilesTableContextMenu.vue
  client/components/pages/files/FiltersDialog.vue
  client/components/pages/files/MediaPreview.vue
  client/components/pages/files/RenameDialog.vue
  client/components/pages/files/RenameDialogFooter.vue
  client/components/pages/files/VisibilityDisplayer.vue
  client/composables/fileTable/useDeleteFile.ts
  client/composables/fileTable/useFilesTable.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/pages/files.vue
  client/public/assets/css/dark-theme.css
  client/types/index.d.ts
  client/unocss.config.ts
  server/src/main/kotlin/com/kamelia/hedera/plugins/Advisors.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
Labels: Enhancement

#136 109 websocket is broken
  client/components/pages/files/FilesTable.vue
  client/composables/fileTable/useRenameFile.ts
  client/composables/useWebsocketAutoConnect.ts
  client/nuxt.config.ts
  client/stores/useAuth.ts
  client/stores/useFilesFilters.ts
  client/stores/useUserSettings.ts
  client/utils/sleep.ts
  server/src/main/kotlin/com/kamelia/hedera/websocket/Handlers.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Tokens.kt
Labels: Bug fix

#137 Files filters and search
  client/components/pages/files/FilesTable.vue
  client/components/pages/files/FiltersDialog.vue
  client/components/ui/topbar/QuotaPreviewer.vue
  client/components/ui/topbar/Topbar.vue
  client/composables/useHumanFileSize.ts
  client/composables/useI18n.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/pages/files.vue
  client/public/assets/css/dark-theme.css
  client/public/assets/css/light-theme.css
  client/utils/filesFilters.ts
  client/utils/sizeUnits.ts
  dev-hedera-docker/docker-compose.yml
  server/src/main/kotlin/com/kamelia/hedera/Application.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/core/pageable/Filter.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Environment.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/main/resources/application.yaml
  server/src/main/resources/db/changelog/db.extensions-declaration.xml
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/main/resources/db/db.changelog-master.xml
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
  server/src/test/kotlin/com/kamelia/hedera/util/DtoTest.kt
  server/src/test/resources/db/data/files.csv
  server/src/test/resources/db/data/users.csv
Labels: Enhancement

#144 Add artificial throttle on failed login
  client/pages/login.vue
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/SessionManager.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Environment.kt
  server/src/main/resources/application.yaml
  server/src/test/kotlin/com/kamelia/hedera/rest/AuthTest.kt
  server/src/test/resources/application-auth-test.yaml
  server/src/test/resources/application.yaml
Labels: Enhancement
