Repository Black-Kamelia/Hedera, pull requests merged in 2023-06, with the labels that each got.

#82 80 extract database configuration in environment variables
  .run/Application.run.xml
  server/src/main/kotlin/com/kamelia/hedera/database/Connection.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Environment.kt
  server/src/main/resources/application.yaml
Labels: Enhancement

#87 Nightly build
  Jenkinsfile
  Jenkinsfile-nightly
  build.gradle.kts
  release/Dockerfile
  release/package.sh
Labels: Technical

#93 Fix CORS
  server/src/main/kotlin/com/kamelia/hedera/Application.kt
Labels: Bug fix

#97 Update CI
  Jenkinsfile
  Jenkinsfile-nightly
Labels: Bug fix, Technical

#95 Fix expired session redirection
  client/app.vue
  client/pages/login.vue
Labels: Bug fix

#102 Fix broken redirections
  client/nuxt.config.ts
  client/pages/[...all].vue
  client/pages/index.vue
Labels: Bug fix

#108 107 services database transaction
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
Labels: Bug fix

#112 Fix dark theme
  client/app.vue
  client/components/ui/debug/ColorPalette.vue
  client/components/ui/navigation/TabNavigation.vue
  client/components/ui/sidebar/Sidebar.vue
  client/composables/useDebug.ts
  client/composables/useTheme.ts
  client/layouts/sidebar.vue
  client/locales/en.yml
  client/locales/fr.yml
  client/nuxt.config.ts
  client/package.json
  client/pages/debug.vue
  client/pages/debug/colors.vue
  client/pages/debug/components.vue
  client/pages/debug/layout.vue
  client/pages/debug/stores.vue
  client/pnpm-lock.yaml
  client/public/assets/css/dark-theme.css
  client/public/assets/css/light-theme.css
  client/public/assets/css/theme.css
  client/scripts/css-minify.cjs
  client/utils/themes.ts
  server/build.gradle.kts
  server/src/test/resources/application-auth-test.yaml
  server/src/test/resources/application.yaml
Labels: Enhancement
