Repository Black-Kamelia/Hedera, pull requests merged in 2023-04, with the labels that each got.

#42 Dark mode
  client/README.md
  client/app.vue
  client/composables/useTheme.ts
  client/layouts/centercard.vue
  client/nuxt.config.ts
  client/package.json
  client/pnpm-lock.yaml
  client/public/dark-theme.css
  client/public/light-theme.css
  client/public/theme.css
  client/utils/themes.ts
Labels: Enhancement, Feature request

#50 Update theme
  client/nuxt.config.ts
  client/public/light-theme.css
  client/public/theme.css
Labels: Enhancement

#52 49 implement refresh and retry in axios config
  .run/Application.run.xml
  build.gradle.kts
  client/app.vue
  client/composables/axios/types.ts
  client/composables/axios/useAxiosInstance.ts
  client/composables/axios/useAxiosMiddlewares.ts
  client/composables/useAPI.ts
  client/env.config.json
  client/env.config.ts
  client/env.dev.config.json
  client/env.dev.config.ts
  client/nuxt.config.ts
  client/package.json
  client/pages/index.vue
  client/pnpm-lock.yaml
  client/stores/useAuth.ts
  client/utils/tokens.ts
  dev-hedera-docker/docker-compose.yml
  gradle.properties
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/hedera/core/Response.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Advisors.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Authentication.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/CORS.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Routing.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Serialization.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/main/kotlin/com/kamelia/hedera/util/FileUtils.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/AuthTest.kt
Labels: Enhancement

#57 Bugfix stored tokens desync on refresh token
  client/composables/axios/useAxiosInstance.ts
  client/composables/axios/useAxiosMiddlewares.ts
  client/composables/useAPI.ts
  client/pages/index.vue
  client/stores/useAuth.ts
  client/utils/tokens.ts
Labels: Bug fix

#59 Event system for auth hooks
  client/app.vue
  client/composables/axios/useAxiosInstance.ts
  client/composables/axios/useAxiosMiddlewares.ts
  client/stores/useAuth.ts
  client/utils/events.ts
Labels: Enhancement

#61 New CI
  Jenkinsfile
  gradle.properties
Labels: Enhancement

#67 Continuous integration optimization
  Jenkinsfile
  build.gradle.kts
  client/build.gradle.kts
  server/build.gradle.kts
Labels: Enhancement

#69 Automatic icon export to iconify set (with optimisation)
  client/components/ui/sidebar/Sidebar.vue
  client/package.json
  client/pnpm-lock.yaml
  client/public/icons/files/logo.svg
  client/public/icons/hedera.json
  client/public/theme.css
  client/scripts/export-icons.cjs
  client/unocss.config.ts
Labels: Enhancement

#64 Websockets
  .run/Application.run.xml
  Jenkinsfile
  dev-hedera-docker/docker-compose.yml
  server/build.gradle.kts
  server/src/main/kotlin/com/kamelia/hedera/Application.kt
  server/src/main/kotlin/com/kamelia/hedera/core/Event.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Serialization.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/WebSockets.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Events.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Environment.kt
  server/src/main/kotlin/com/kamelia/hedera/util/WebSocketUtils.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Handlers.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/websocket/Tokens.kt
  server/src/main/resources/application.yaml
  server/src/test/resources/application-auth-test.yaml
  server/src/test/resources/application.yaml
Labels: Enhancement, Feature request

#71 Handle account state (enabled)
  client/components/input/FormInputText.vue
  client/components/input/InputText.vue
  client/components/ui/sidebar/Sidebar.vue
  client/components/ui/sidebar/SidebarButton.vue
  client/locales/en.yml
  client/locales/fr.yml
  client/middleware/auth.ts
  client/pages/login.vue
  client/pages/reset-password.vue
  server/src/main/kotlin/com/kamelia/hedera/core/Errors.kt
  server/src/main/kotlin/com/kamelia/hedera/core/Exceptions.kt
  server/src/main/kotlin/com/kamelia/hedera/plugins/Advisors.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/auth/SessionManager.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Routes.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/test/kotlin/com/kamelia/hedera/TestUtils.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/AuthTest.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
  server/src/test/kotlin/com/kamelia/hedera/rest/UserTest.kt
  server/src/test/resources/db/data/users.csv
Labels: Bug fix

#73 Websocket front
  client/app.vue
  client/components/input/FormCheckbox.vue
  client/components/input/FormInputText.vue
  client/components/input/InputOTP.vue
  client/components/ui/sidebar/SidebarButton.vue
  client/components/ui/topbar/QuotaPreviewer.vue
  client/composables/axios/useAxiosFactory.ts
  client/composables/useWebsocketAutoConnect.ts
  client/env.dev.config.json
  client/nuxt.config.ts
  client/pages/login.vue
  client/types/index.d.ts
  client/utils/websocketEvents.ts
Labels: Enhancement, Feature request
