Repository Black-Kamelia/Hedera, pull requests merged in 2023-12, with the labels that each got.

#222 Encrypt personal tokens
  server/src/main/kotlin/com/kamelia/hedera/rest/file/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/token/DTO.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/token/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/token/Service.kt
  server/src/main/kotlin/com/kamelia/hedera/rest/user/Entity.kt
  server/src/main/kotlin/com/kamelia/hedera/util/Extensions.kt
  server/src/main/resources/db/changelog/db.schema-init.xml
  server/src/main/resources/db/data/default-personal-tokens.csv
  server/src/test/kotlin/com/kamelia/hedera/rest/FileTest.kt
  server/src/test/resources/db/data/personal-tokens.csv
Labels: Enhancement, Security

#224 Media preview
  client/components/pages/files/FilesTable.vue
  client/components/pages/files/preview/MediaPreview.vue
  client/components/pages/files/preview/MediaThumbnail.vue
  client/components/pages/files/preview/media/AudioPreview.vue
  client/components/pages/files/preview/media/ImagePreview.vue
  client/components/pages/files/preview/media/VideoPreview.vue
  client/composables/useThumbnail.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/package.json
  client/pnpm-lock.yaml
  client/utils/mimeTypes.ts
Labels: Feature

#232 Revamp upload page
  client/components/pages/files/EditCustomLinkDialog.vue
  client/components/pages/files/preview/MediaPreview.vue
  client/components/pages/files/preview/MediaThumbnail.vue
  client/components/pages/files/preview/Thumbnail.vue
  client/components/pages/files/preview/media/AudioPreview.vue
  client/components/pages/files/preview/media/ImagePreview.vue
  client/components/pages/files/preview/media/VideoPreview.vue
  client/components/pages/upload/Dropzone.vue
  client/components/pages/upload/FileDrop.vue
  client/components/pages/upload/FileDropFilesSection.vue
  client/components/pages/upload/FileTile.vue
  client/components/pages/upload/FileUpload.vue
  client/composables/useObjectURL.ts
  client/locales/en.yml
  client/locales/fr.yml
  client/pages/upload.vue
  client/public/assets/css/dark-theme-custom.css
  client/public/assets/css/light-theme-custom.css
  client/types/index.d.ts
Labels: Enhancement, UI

#236 Update Nuxt version
  client/.vscode/settings.json
  client/package.json
  client/pnpm-lock.yaml
Labels: Technical

#238 Fix file size input UX
  client/components/ui/files/FileSizeInput.vue
Labels: Bug fix
